Update iics_deployment.yml

diff --git a/.github/workflows/iics_deployment.yml b/.github/workflows/iics_deployment.yml
--- a/.github/workflows/iics_deployment.yml
+++ b/.github/workflows/iics_deployment.yml
@@ -1,3 +1,4 @@
+
 name: Promote Dev to UAT
 
 on:
@@ -82,12 +83,11 @@ jobs:
         run: |
           git config --global user.name "Brandon Bir"
           git config --global user.email "bbird@informatica.com"
-          
 
       - name: Set GitHub token for authentication
         run: |
           cd ./IICS-CDP-CICD-demo
-          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
+          git remote set-url origin https://x-access-token:${{GH_TOKEN}}@github.com/${{ github.repository }}
 
       - name: Cherry-pick Commit from Dev and Push to UAT
         run: |
@@ -99,7 +99,17 @@ jobs:
             git checkout -b qa main
             git push origin qa
           fi
-          git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH}
+
+          git cherry-pick --strategy=recursive -X theirs ${{COMMIT_HASH}} || {
+            if git status | grep -q "nothing to commit"; then
+              echo "Cherry-pick resulted in no changes. Skipping."
+              git cherry-pick --skip
+            else
+              echo "Cherry-pick failed due to conflicts."
+              exit 1
+            fi
+          }
+
           git push origin HEAD:qa
 
       - name: Get Latest Changes to UAT
